bit_knn_classify:  instances.cpp instances.hpp bit_knn.cpp bit_knn.hpp bit_knn_classify.cpp
	g++ -O3 -Wall -msse4.2 -std=c++0x -o bit_knn_classify bit_knn_classify.cpp instances.cpp bit_knn.cpp

clean:
	rm bit_knn_classify
